// utils/constants.js (確保內容完整)

export const CRIMINAL_KEYWORDS_TITLE = ['違反', '妨害', '殺人', '傷害', '竊盜', '詐欺', '貪污', '瀆職', '偽造文書', '毒品', '槍砲', '公共危險', '過失致死', '背信'];
export const CIVIL_KEYWORDS_TITLE = ['給付', '返還', '確認', '分割', '所有權', '抵押權', '租賃', '買賣', '承攬', '工程款', '醫療疏失', '離婚', '繼承', '監護', '票據', '債務不履行', '侵權行為損害賠償'];

export const NEUTRAL_OUTCOME_CODES = {
  PROCEDURAL_NEUTRAL: 'PROCEDURAL_NEUTRAL',
  SETTLEMENT_NEUTRAL: 'SETTLEMENT_NEUTRAL',
  WITHDRAWAL_NEUTRAL: 'WITHDRAWAL_NEUTRAL',
  NOT_APPLICABLE_OR_UNKNOWN_NEUTRAL: 'NOT_APPLICABLE_OR_UNKNOWN_NEUTRAL',
  UNKNOWN_NEUTRAL: 'UNKNOWN_NEUTRAL',
  // Civil Plaintiff
  CIVIL_P_WIN_FULL: 'CIVIL_P_WIN_FULL',
  CIVIL_P_WIN_MAJOR: 'CIVIL_P_WIN_MAJOR',
  CIVIL_P_WIN_PARTIAL: 'CIVIL_P_WIN_PARTIAL',
  CIVIL_P_WIN_MINOR: 'CIVIL_P_WIN_MINOR',
  CIVIL_P_LOSE_FULL: 'CIVIL_P_LOSE_FULL',
  // Civil Defendant
  CIVIL_D_WIN_FULL: 'CIVIL_D_WIN_FULL',
  CIVIL_D_MITIGATE_MAJOR: 'CIVIL_D_MITIGATE_MAJOR',
  CIVIL_D_MITIGATE_PARTIAL: 'CIVIL_D_MITIGATE_PARTIAL',
  CIVIL_D_MITIGATE_MINOR: 'CIVIL_D_MITIGATE_MINOR',
  CIVIL_D_LOSE_FULL: 'CIVIL_D_LOSE_FULL',
  // Civil Ruling
  CIVIL_RULING_GRANTED: 'CIVIL_RULING_GRANTED',
  CIVIL_RULING_DISMISSED: 'CIVIL_RULING_DISMISSED',
  // Generic
  GENERIC_WIN_FULL: 'GENERIC_WIN_FULL',
  GENERIC_WIN_PARTIAL: 'GENERIC_WIN_PARTIAL',
  GENERIC_LOSE_FULL: 'GENERIC_LOSE_FULL',
  // Civil Uncategorized
  CIVIL_UNCATEGORIZED_NEUTRAL: 'CIVIL_UNCATEGORIZED_NEUTRAL',
  // Criminal
  CRIMINAL_ACQUITTED: 'CRIMINAL_ACQUITTED',
  CRIMINAL_GUILTY_SIG_REDUCED: 'CRIMINAL_GUILTY_SIG_REDUCED',
  CRIMINAL_GUILTY_SLIGHT_REDUCED: 'CRIMINAL_GUILTY_SLIGHT_REDUCED',
  CRIMINAL_GUILTY_PROBATION: 'CRIMINAL_GUILTY_PROBATION',
  CRIMINAL_GUILTY_FINE_CONVERTIBLE: 'CRIMINAL_GUILTY_FINE_CONVERTIBLE',
  CRIMINAL_GUILTY_FINE_ONLY: 'CRIMINAL_GUILTY_FINE_ONLY',
  CRIMINAL_GUILTY_AGGRAVATED: 'CRIMINAL_GUILTY_AGGRAVATED',
  CRIMINAL_GUILTY_AS_EXPECTED_OR_SENTENCED: 'CRIMINAL_GUILTY_AS_EXPECTED_OR_SENTENCED',
  CRIMINAL_RULING_BAIL_GRANTED: 'CRIMINAL_RULING_BAIL_GRANTED',
  CRIMINAL_RULING_DETENTION_ORDERED: 'CRIMINAL_RULING_DETENTION_ORDERED',
  CRIMINAL_CHARGE_DISMISSED_NO_PROSECUTION: 'CRIMINAL_CHARGE_DISMISSED_NO_PROSECUTION',
  CRIMINAL_CHARGE_DISMISSED_NOT_ACCEPTED: 'CRIMINAL_CHARGE_DISMISSED_NOT_ACCEPTED',
  CRIMINAL_UNCATEGORIZED_NEUTRAL: 'CRIMINAL_UNCATEGORIZED_NEUTRAL',
  // Administrative
  ADMIN_RULING_STAY_GRANTED: 'ADMIN_RULING_STAY_GRANTED',
  ADMIN_RULING_STAY_DENIED: 'ADMIN_RULING_STAY_DENIED',
  ADMIN_RULING_UNCATEGORIZED_NEUTRAL: 'ADMIN_RULING_UNCATEGORIZED_NEUTRAL',
  ADMIN_WIN_REVOKE_FULL: 'ADMIN_WIN_REVOKE_FULL',
  ADMIN_WIN_REVOKE_PARTIAL: 'ADMIN_WIN_REVOKE_PARTIAL',
  ADMIN_LOSE_DISMISSED: 'ADMIN_LOSE_DISMISSED',
  ADMIN_WIN_OBLIGATION: 'ADMIN_WIN_OBLIGATION',
  ADMIN_JUDGMENT_UNCATEGORIZED_NEUTRAL: 'ADMIN_JUDGMENT_UNCATEGORIZED_NEUTRAL',
};

export const FINAL_STAT_KEYS = {
  TOTAL: 'total',
  FAVORABLE_FULL: 'FAVORABLE_FULL_COUNT',
  FAVORABLE_PARTIAL: 'FAVORABLE_PARTIAL_COUNT',
  UNFAVORABLE_FULL: 'UNFAVORABLE_FULL_COUNT',
  NEUTRAL_SETTLEMENT: 'NEUTRAL_SETTLEMENT_COUNT',
  PROCEDURAL: 'PROCEDURAL_COUNT',
  OTHER_UNKNOWN: 'OTHER_UNKNOWN_COUNT',
};