// utils/constants.js (確保內容完整)

export const CRIMINAL_KEYWORDS_TITLE = ['違反', '妨害', '殺人', '傷害', '竊盜', '詐欺', '貪污', '瀆職', '偽造文書', '毒品', '槍砲', '公共危險', '過失致死', '背信'];
export const CIVIL_KEYWORDS_TITLE = ['給付', '返還', '確認', '分割', '所有權', '抵押權', '租賃', '買賣', '承攬', '工程款', '醫療疏失', '離婚', '繼承', '監護', '票據', '債務不履行', '侵權行為損害賠償'];

export const NEUTRAL_OUTCOME_CODES = {
  PROCEDURAL_NEUTRAL: 'PROCEDURAL_NEUTRAL',
  SETTLEMENT_NEUTRAL: 'SETTLEMENT_NEUTRAL',
  WITHDRAWAL_NEUTRAL: 'WITHDRAWAL_NEUTRAL',
  NOT_APPLICABLE_OR_UNKNOWN_NEUTRAL: 'NOT_APPLICABLE_OR_UNKNOWN_NEUTRAL',
  UNKNOWN_NEUTRAL: 'UNKNOWN_NEUTRAL',
  // Civil Plaintiff
  CIVIL_P_WIN_FULL: 'CIVIL_P_WIN_FULL',
  CIVIL_P_WIN_MAJOR: 'CIVIL_P_WIN_MAJOR',
  CIVIL_P_WIN_PARTIAL: 'CIVIL_P_WIN_PARTIAL',
  CIVIL_P_WIN_MINOR: 'CIVIL_P_WIN_MINOR',
  CIVIL_P_LOSE_FULL: 'CIVIL_P_LOSE_FULL',
  // Civil Defendant
  CIVIL_D_WIN_FULL: 'CIVIL_D_WIN_FULL',
  CIVIL_D_MITIGATE_MAJOR: 'CIVIL_D_MITIGATE_MAJOR',
  CIVIL_D_MITIGATE_PARTIAL: 'CIVIL_D_MITIGATE_PARTIAL',
  CIVIL_D_MITIGATE_MINOR: 'CIVIL_D_MITIGATE_MINOR',
  CIVIL_D_LOSE_FULL: 'CIVIL_D_LOSE_FULL',
  // Civil Ruling
  CIVIL_RULING_GRANTED: 'CIVIL_RULING_GRANTED',
  CIVIL_RULING_DISMISSED: 'CIVIL_RULING_DISMISSED',
  // Generic
  GENERIC_WIN_FULL: 'GENERIC_WIN_FULL',
  GENERIC_WIN_PARTIAL: 'GENERIC_WIN_PARTIAL',
  GENERIC_LOSE_FULL: 'GENERIC_LOSE_FULL',
  // Civil Uncategorized
  CIVIL_UNCATEGORIZED_NEUTRAL: 'CIVIL_UNCATEGORIZED_NEUTRAL',
  // Criminal
  CRIMINAL_ACQUITTED: 'CRIMINAL_ACQUITTED',
  CRIMINAL_GUILTY_SIG_REDUCED: 'CRIMINAL_GUILTY_SIG_REDUCED',
  CRIMINAL_GUILTY_SLIGHT_REDUCED: 'CRIMINAL_GUILTY_SLIGHT_REDUCED',
  CRIMINAL_GUILTY_PROBATION: 'CRIMINAL_GUILTY_PROBATION',
  CRIMINAL_GUILTY_FINE_CONVERTIBLE: 'CRIMINAL_GUILTY_FINE_CONVERTIBLE',
  CRIMINAL_GUILTY_FINE_ONLY: 'CRIMINAL_GUILTY_FINE_ONLY',
  CRIMINAL_GUILTY_AGGRAVATED: 'CRIMINAL_GUILTY_AGGRAVATED',
  CRIMINAL_GUILTY_AS_EXPECTED_OR_SENTENCED: 'CRIMINAL_GUILTY_AS_EXPECTED_OR_SENTENCED',
  CRIMINAL_RULING_BAIL_GRANTED: 'CRIMINAL_RULING_BAIL_GRANTED',
  CRIMINAL_RULING_DETENTION_ORDERED: 'CRIMINAL_RULING_DETENTION_ORDERED',
  CRIMINAL_CHARGE_DISMISSED_NO_PROSECUTION: 'CRIMINAL_CHARGE_DISMISSED_NO_PROSECUTION',
  CRIMINAL_CHARGE_DISMISSED_NOT_ACCEPTED: 'CRIMINAL_CHARGE_DISMISSED_NOT_ACCEPTED',
  CRIMINAL_UNCATEGORIZED_NEUTRAL: 'CRIMINAL_UNCATEGORIZED_NEUTRAL',
  // Administrative
  ADMIN_RULING_STAY_GRANTED: 'ADMIN_RULING_STAY_GRANTED',
  ADMIN_RULING_STAY_DENIED: 'ADMIN_RULING_STAY_DENIED',
  ADMIN_RULING_UNCATEGORIZED_NEUTRAL: 'ADMIN_RULING_UNCATEGORIZED_NEUTRAL',
  ADMIN_WIN_REVOKE_FULL: 'ADMIN_WIN_REVOKE_FULL',
  ADMIN_WIN_REVOKE_PARTIAL: 'ADMIN_WIN_REVOKE_PARTIAL',
  ADMIN_LOSE_DISMISSED: 'ADMIN_LOSE_DISMISSED',
  ADMIN_WIN_OBLIGATION: 'ADMIN_WIN_OBLIGATION',
  ADMIN_JUDGMENT_UNCATEGORIZED_NEUTRAL: 'ADMIN_JUDGMENT_UNCATEGORIZED_NEUTRAL',
};

export const FINAL_STAT_KEYS = {
  TOTAL: 'total',
  FAVORABLE_FULL: 'FAVORABLE_FULL_COUNT',
  FAVORABLE_PARTIAL: 'FAVORABLE_PARTIAL_COUNT',
  UNFAVORABLE_FULL: 'UNFAVORABLE_FULL_COUNT',
  NEUTRAL_SETTLEMENT: 'NEUTRAL_SETTLEMENT_COUNT',
  PROCEDURAL: 'PROCEDURAL_COUNT',
  OTHER_UNKNOWN: 'OTHER_UNKNOWN_COUNT',
};

export const JUDGE_CENTRIC_OUTCOMES = {
  // 民事 (Civil)
  CIVIL_PLAINTIFF_WIN_FULL: 'CIVIL_PLAINTIFF_WIN_FULL',           // 原告訴請完全支持
  CIVIL_PLAINTIFF_WIN_PARTIAL: 'CIVIL_PLAINTIFF_WIN_PARTIAL',     // 原告訴請部分支持
  CIVIL_PLAINTIFF_CLAIM_DISMISSED: 'CIVIL_PLAINTIFF_CLAIM_DISMISSED', // 原告訴請駁回 (實質)
  CIVIL_DEFENDANT_COUNTERCLAIM_WIN: 'CIVIL_DEFENDANT_COUNTERCLAIM_WIN', // 被告反訴成立 (如果能判斷)
  CIVIL_SETTLEMENT: 'CIVIL_SETTLEMENT',                         // 和解/調解成立
  CIVIL_PLAINTIFF_WITHDRAWAL: 'CIVIL_PLAINTIFF_WITHDRAWAL',         // 原告撤回
  CIVIL_PROCEDURAL_DISMISSAL: 'CIVIL_PROCEDURAL_DISMISSAL',       // 程序性駁回 (非實質)
  CIVIL_OTHER: 'CIVIL_OTHER',                                   // 其他民事結果

  // 刑事 (Criminal)
  CRIMINAL_DEFENDANT_ACQUITTED: 'CRIMINAL_DEFENDANT_ACQUITTED',   // 被告無罪
  CRIMINAL_DEFENDANT_IMMUNITY: 'CRIMINAL_DEFENDANT_IMMUNITY',     // 被告免訴
  CRIMINAL_DEFENDANT_NOT_ACCEPTED: 'CRIMINAL_DEFENDANT_NOT_ACCEPTED', // 案件不受理 (刑事)
  CRIMINAL_PROSECUTION_DISMISSED: 'CRIMINAL_PROSECUTION_DISMISSED', // 公訴/自訴駁回
  CRIMINAL_DEFENDANT_GUILTY_PROBATION: 'CRIMINAL_DEFENDANT_GUILTY_PROBATION', // 被告有罪 - 緩刑
  CRIMINAL_DEFENDANT_GUILTY_FINE: 'CRIMINAL_DEFENDANT_GUILTY_FINE',       // 被告有罪 - 罰金
  CRIMINAL_DEFENDANT_GUILTY_IMPRISONMENT: 'CRIMINAL_DEFENDANT_GUILTY_IMPRISONMENT',// 被告有罪 - 徒刑 (或其他自由刑)
  CRIMINAL_DEFENDANT_GUILTY_MITIGATED: 'CRIMINAL_DEFENDANT_GUILTY_MITIGATED',  // 被告有罪 - 但獲減刑
  CRIMINAL_DEFENDANT_GUILTY_OTHER: 'CRIMINAL_DEFENDANT_GUILTY_OTHER',    // 被告有罪 - 其他情況
  CRIMINAL_PROCEDURAL: 'CRIMINAL_PROCEDURAL',                     // 其他刑事程序性結果
  CRIMINAL_OTHER: 'CRIMINAL_OTHER',                               // 其他刑事結果

  // 行政 (Administrative)
  ADMIN_PLAINTIFF_WIN_REVOKE_FULL: 'ADMIN_PLAINTIFF_WIN_REVOKE_FULL', // 原告勝訴 - 原處分完全撤銷
  ADMIN_PLAINTIFF_WIN_REVOKE_PARTIAL: 'ADMIN_PLAINTIFF_WIN_REVOKE_PARTIAL',// 原告勝訴 - 原處分部分撤銷
  ADMIN_PLAINTIFF_WIN_OBLIGATION: 'ADMIN_PLAINTIFF_WIN_OBLIGATION',    // 原告勝訴 - 命機關做成行政處分
  ADMIN_PLAINTIFF_CLAIM_DISMISSED: 'ADMIN_PLAINTIFF_CLAIM_DISMISSED',   // 原告訴請駁回 (實質)
  ADMIN_SETTLEMENT: 'ADMIN_SETTLEMENT',                             // 和解
  ADMIN_PLAINTIFF_WITHDRAWAL: 'ADMIN_PLAINTIFF_WITHDRAWAL',             // 原告撤回
  ADMIN_PROCEDURAL_DISMISSAL: 'ADMIN_PROCEDURAL_DISMISSAL',           // 程序性駁回
  ADMIN_OTHER: 'ADMIN_OTHER',                                       // 其他行政結果

  // 通用
  PROCEDURAL_RULING: 'PROCEDURAL_RULING', // 通用程序性裁定 (如果 is_ruling 為是)
  UNKNOWN_OUTCOME: 'UNKNOWN_OUTCOME',     // 未知或無法分類
};